#!/usr/bin/env node
// Generates src/client/icons.ts: maps every `mdi-*` name used by the app
// (plus Vuetify's built-in icon aliases) to tree-shaken @mdi/js path data,
// so the ~2.2 MB MDI webfont can be dropped from the bundle.
// Exits non-zero if any used name has no counterpart in @mdi/js.
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')

const fontSetPath = path.join(root, 'node_modules/vuetify/lib/iconsets/mdi.js')
const fontAliasSource = fs.readFileSync(fontSetPath, 'utf8')
const aliasNames = [...fontAliasSource.matchAll(/'(mdi-[a-z0-9-]+)'/g)].map(m => m[1])

function walk (dir, acc = []) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name)
    if (entry.isDirectory()) walk(full, acc)
    else if (/\.(vue|ts|html)$/.test(entry.name)) acc.push(full)
  }
  return acc
}

const usedNames = []
for (const file of walk(path.join(root, 'src/client'))) {
  // Skip the generated file itself, or it would only ever re-emit its own map.
  if (file.endsWith('icons.ts')) continue
  const text = fs.readFileSync(file, 'utf8')
  for (const m of text.matchAll(/mdi-[a-z0-9-]+/g)) usedNames.push(m[0])
}

const names = [...new Set([...aliasNames, ...usedNames])].sort()

const mdi = await import('@mdi/js')
const toExport = n => 'mdi' + n.slice(4).split('-').map(w => w[0].toUpperCase() + w.slice(1)).join('')

const entries = []
const missing = []
for (const name of names) {
  const exp = toExport(name)
  if (typeof mdi[exp] === 'string') entries.push([name, exp])
  else missing.push(`${name} -> ${exp}`)
}

if (missing.length) {
  console.error('gen-icons: no @mdi/js counterpart for:\n  ' + missing.join('\n  '))
  process.exit(1)
}

const imports = entries.map(([, exp]) => `  ${exp}`).join(',\n')
const map = entries.map(([name, exp]) => `  '${name}': ${exp}`).join(',\n')

const out = `// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
//
// Renders the \`mdi-*\` names used by this app as inline SVG, replacing the
// full Material Design Icons webfont (~2.2 MB of woff/ttf plus a ~650 KB
// stylesheet) with the ${entries.length} glyphs actually referenced.
//
// Only the icons below are imported from @mdi/js, which keeps Rollup able to
// tree-shake the rest of the package.
import { defineComponent, h, type Component, type PropType } from 'vue'
import type { IconSet } from 'vuetify'
import {
${imports},
} from '@mdi/js'

/** Mirrors Vuetify's own \`IconValue\`. */
export type IconValue = string | readonly string[]

export const iconPaths: Record<string, string> = {
${map},
}

/**
 * Drop-in replacement for Vuetify's SVG icon set component.
 *
 * Vuetify resolves \`mdi-check\` by handing the raw name to this component
 * (a \`set:name\` colon prefix is the only syntax it splits on), so every
 * \`mdi-*\` string in a template keeps working unchanged — the lookup happens
 * here rather than in the templates.
 */
export const VSvgIcon = defineComponent({
  name: 'VSvgIcon',
  props: {
    tag: { type: [String, Object, Function] as PropType<string | Component>, default: 'i' },
    icon: { type: [String, Array] as PropType<IconValue>, default: '' },
    disabled: Boolean,
  },
  setup (props, { attrs }) {
    return () => {
      const value = props.icon
      const name = typeof value === 'string' ? value : String(value?.[0] ?? '')
      const path = iconPaths[name]
      if (path === undefined) {
        // Loud in dev, silent in production: an unmapped name renders an empty
        // box rather than crashing the view.
        console.warn(\`[icons] unmapped icon name: \${name}\`)
      }
      return h(props.tag, { ...attrs }, [
        h(
          'svg',
          {
            class: 'v-icon__svg',
            xmlns: 'http://www.w3.org/2000/svg',
            viewBox: '0 0 24 24',
            role: 'img',
            'aria-hidden': 'true',
          },
          path === undefined ? [] : [h('path', { d: path })],
        ),
      ])
    }
  },
})

export const mdi: IconSet = { component: VSvgIcon as unknown as IconSet['component'] }
`

fs.writeFileSync(path.join(root, 'src/client/icons.ts'), out)
console.log(`gen-icons: wrote src/client/icons.ts with ${entries.length} icons`)
console.log(`  from app usage: ${new Set(usedNames).size}, from Vuetify aliases: ${new Set(aliasNames).size}`)