// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
//
// Renders the `mdi-*` names used by this app as inline SVG, replacing the
// full Material Design Icons webfont (~2.2 MB of woff/ttf plus a ~650 KB
// stylesheet) with the 66 glyphs actually referenced.
//
// Only the icons below are imported from @mdi/js, which keeps Rollup able to
// tree-shake the rest of the package.
import { defineComponent, h, type Component, type PropType } from 'vue'
import type { IconSet } from 'vuetify'
import {
  mdiAccountCircleOutline,
  mdiAlertCircle,
  mdiAppleKeyboardCommand,
  mdiAppleKeyboardControl,
  mdiAppleKeyboardOption,
  mdiAppleKeyboardShift,
  mdiArrowDown,
  mdiArrowLeft,
  mdiArrowRight,
  mdiArrowUp,
  mdiBackspace,
  mdiCached,
  mdiCalendar,
  mdiCheck,
  mdiCheckCircle,
  mdiCheckboxBlankOutline,
  mdiCheckboxMarked,
  mdiChevronDown,
  mdiChevronLeft,
  mdiChevronRight,
  mdiChevronUp,
  mdiCircle,
  mdiClose,
  mdiCloseCircle,
  mdiCloudUpload,
  mdiDatabaseImport,
  mdiDeleteOutline,
  mdiEyeOffOutline,
  mdiEyeOutline,
  mdiEyedropper,
  mdiFullscreen,
  mdiFullscreenExit,
  mdiGithub,
  mdiInformation,
  mdiKeyboardReturn,
  mdiKeyboardSpace,
  mdiLinkVariant,
  mdiLogout,
  mdiMagnify,
  mdiMenu,
  mdiMenuDown,
  mdiMenuRight,
  mdiMinus,
  mdiMinusBox,
  mdiOpenInNew,
  mdiPageFirst,
  mdiPageLast,
  mdiPalette,
  mdiPaperclip,
  mdiPause,
  mdiPencil,
  mdiPencilOutline,
  mdiPlay,
  mdiPlus,
  mdiRadioboxBlank,
  mdiRadioboxMarked,
  mdiRefresh,
  mdiShieldCheckOutline,
  mdiStar,
  mdiStarHalfFull,
  mdiStarOutline,
  mdiUnfoldMoreHorizontal,
  mdiVolumeHigh,
  mdiVolumeLow,
  mdiVolumeMedium,
  mdiVolumeVariantOff,
} from '@mdi/js'

/** Mirrors Vuetify's own `IconValue`. */
export type IconValue = string | readonly string[]

export const iconPaths: Record<string, string> = {
  'mdi-account-circle-outline': mdiAccountCircleOutline,
  'mdi-alert-circle': mdiAlertCircle,
  'mdi-apple-keyboard-command': mdiAppleKeyboardCommand,
  'mdi-apple-keyboard-control': mdiAppleKeyboardControl,
  'mdi-apple-keyboard-option': mdiAppleKeyboardOption,
  'mdi-apple-keyboard-shift': mdiAppleKeyboardShift,
  'mdi-arrow-down': mdiArrowDown,
  'mdi-arrow-left': mdiArrowLeft,
  'mdi-arrow-right': mdiArrowRight,
  'mdi-arrow-up': mdiArrowUp,
  'mdi-backspace': mdiBackspace,
  'mdi-cached': mdiCached,
  'mdi-calendar': mdiCalendar,
  'mdi-check': mdiCheck,
  'mdi-check-circle': mdiCheckCircle,
  'mdi-checkbox-blank-outline': mdiCheckboxBlankOutline,
  'mdi-checkbox-marked': mdiCheckboxMarked,
  'mdi-chevron-down': mdiChevronDown,
  'mdi-chevron-left': mdiChevronLeft,
  'mdi-chevron-right': mdiChevronRight,
  'mdi-chevron-up': mdiChevronUp,
  'mdi-circle': mdiCircle,
  'mdi-close': mdiClose,
  'mdi-close-circle': mdiCloseCircle,
  'mdi-cloud-upload': mdiCloudUpload,
  'mdi-database-import': mdiDatabaseImport,
  'mdi-delete-outline': mdiDeleteOutline,
  'mdi-eye-off-outline': mdiEyeOffOutline,
  'mdi-eye-outline': mdiEyeOutline,
  'mdi-eyedropper': mdiEyedropper,
  'mdi-fullscreen': mdiFullscreen,
  'mdi-fullscreen-exit': mdiFullscreenExit,
  'mdi-github': mdiGithub,
  'mdi-information': mdiInformation,
  'mdi-keyboard-return': mdiKeyboardReturn,
  'mdi-keyboard-space': mdiKeyboardSpace,
  'mdi-link-variant': mdiLinkVariant,
  'mdi-logout': mdiLogout,
  'mdi-magnify': mdiMagnify,
  'mdi-menu': mdiMenu,
  'mdi-menu-down': mdiMenuDown,
  'mdi-menu-right': mdiMenuRight,
  'mdi-minus': mdiMinus,
  'mdi-minus-box': mdiMinusBox,
  'mdi-open-in-new': mdiOpenInNew,
  'mdi-page-first': mdiPageFirst,
  'mdi-page-last': mdiPageLast,
  'mdi-palette': mdiPalette,
  'mdi-paperclip': mdiPaperclip,
  'mdi-pause': mdiPause,
  'mdi-pencil': mdiPencil,
  'mdi-pencil-outline': mdiPencilOutline,
  'mdi-play': mdiPlay,
  'mdi-plus': mdiPlus,
  'mdi-radiobox-blank': mdiRadioboxBlank,
  'mdi-radiobox-marked': mdiRadioboxMarked,
  'mdi-refresh': mdiRefresh,
  'mdi-shield-check-outline': mdiShieldCheckOutline,
  'mdi-star': mdiStar,
  'mdi-star-half-full': mdiStarHalfFull,
  'mdi-star-outline': mdiStarOutline,
  'mdi-unfold-more-horizontal': mdiUnfoldMoreHorizontal,
  'mdi-volume-high': mdiVolumeHigh,
  'mdi-volume-low': mdiVolumeLow,
  'mdi-volume-medium': mdiVolumeMedium,
  'mdi-volume-variant-off': mdiVolumeVariantOff,
}

/**
 * Drop-in replacement for Vuetify's SVG icon set component.
 *
 * Vuetify resolves `mdi-check` by handing the raw name to this component
 * (a `set:name` colon prefix is the only syntax it splits on), so every
 * `mdi-*` string in a template keeps working unchanged — the lookup happens
 * here rather than in the templates.
 */
export const VSvgIcon = defineComponent({
  name: 'VSvgIcon',
  props: {
    tag: { type: [String, Object, Function] as PropType<string | Component>, default: 'i' },
    icon: { type: [String, Array] as PropType<IconValue>, default: '' },
    disabled: Boolean,
  },
  setup (props, { attrs }) {
    return () => {
      const value = props.icon
      const name = typeof value === 'string' ? value : String(value?.[0] ?? '')
      const path = iconPaths[name]
      if (path === undefined) {
        // Loud in dev, silent in production: an unmapped name renders an empty
        // box rather than crashing the view.
        console.warn(`[icons] unmapped icon name: ${name}`)
      }
      return h(props.tag, { ...attrs }, [
        h(
          'svg',
          {
            class: 'v-icon__svg',
            xmlns: 'http://www.w3.org/2000/svg',
            viewBox: '0 0 24 24',
            role: 'img',
            'aria-hidden': 'true',
          },
          path === undefined ? [] : [h('path', { d: path })],
        ),
      ])
    }
  },
})

export const mdi: IconSet = { component: VSvgIcon as unknown as IconSet['component'] }
